### PR TITLE
First_commit: Preprocessing and Modeling

### PR DESCRIPTION
**Pull request by zubbix**
Some preprocessing and few models applied. Please review and make corrections.
File: Edited: Preprocessing & Modeling(Heatmap added)

Steps taken:

1) Imported necessary libraries
2) 50% of the original dataset were randomly sampled: Check out the Cst_Cnt field to see the randomness
3) Relevant features were selected, meaning others were dropped. The underlying reason for dropping features were:

A) Some features were categorical that had no direct relevance to salinity prediction. some were quality check records, record indicators and so on
B) Some features were a (or almost) copy of each other. These include: (Depthm and R_Depth), (O2ml_L and R_Oxy_µmol/Kg), (Salnty and R_SALINITY) and so on. Having them can lead to high multiocollinearity.  A heat map as well as an external link was added to justify claim

4) Dealt with missing values using mean replacement technique
5) Check for normality. Target variable (salnty) showed signs of a normal distribution as well as some features. 

****Went further to check few models to see how the result of the preprocessing performed****
 
6) Split (test_size= 20%) and Normalization (MinMaxScaler)
7) Modeling

A) LinearRegression
B) DecisionTree
C) Cross validation( Cross_val_Score)

#4

### CODE REVIEW

**Review by Oluwatobi09 — COMMENTED** [review]
I think you should upload a python(.py file) file instead of the jupyter notebook, it makes the code more coherent and easy for others to understand

**Comment by waleblaq** [comment]
i think we should take it according to how it is on the todo list

**Comment by zubbix** [comment]
> I think you should upload a python(.py file) file instead of the jupyter notebook, it makes the code more coherent and easy for others to understand

Didn't turn out well?? Sorry about that. I'm still learning the ropes. I actually used github to upload the file instead of the terminal to push it. I'll see to that soon. Thanks

**Comment by waleblaq** [comment]
> I think you should upload a python(.py file) file instead of the jupyter notebook, it makes the code more coherent and easy for others to understand

go to the side and click the 3 dots and click view file

**Comment by zubbix** [comment]
> i think we should take it according to how it is on the todo list

Alright bro.. I'll edit it and resend. Thanks

**Comment by Justus-coded** [comment]
Great job @zubbix . 

From your preprocessing, it seems you dropped all the categorical features. Does this mean that no categorical feature was relevant to the target variable. Also could you be more specific on some of the data quality checks done and criteria used for dropping the columns. 

Lastly, you could add a heatmap to show some of your findings and validate your decisions. Thanks.

**Comment by zubbix** [comment]
> Great job @zubbix .
> 
> From your preprocessing, it seems you dropped all the categorical features. Does this mean that no categorical feature was relevant to the target variable. Also could you be more specific on some of the data quality checks done and criteria used for dropping the columns.
> 
> Lastly, you could add a heat map to show some of your findings and validate your decisions. Thanks.

Thanks @Justus-coded ...

Yes I dropped all the categorical features based on intuition after doing a little digging up on the dataset what the variables mean and how they relate to each other: [https://oceaninformatics.ucsd.edu/datazoo/catalogs/pallter/datasets/78/datatables/269](url) 

For the heat map, I have included it in the edited work.

**Pull request merged**
