### PR TITLE
Dataset upload

### LINKED ISSUE #1: Upload of Dataset
the data set needs to be uploaded to the repo to enable other team member fork the project

### PR DESCRIPTION
**Pull request by BBimie**
The two datasets are too large to be uploaded directly to Github, so I added the link to the Kaggle download in the readme. Download the datasets from Kaggle, but the data descriptions are present in the data folder.

Closed #1

### CODE REVIEW

**Comment by Justus-coded** [comment]
> The two datasets are too large to be uploaded directly to Github, so I added the link to the Kaggle download in the readme. Download the datasets from Kaggle, but the data descriptions are present in the data folder.
> 
> Closed #1

**Comment by Justus-coded** [comment]
It's okay to add the link since the datasets are large. Great job Bimbo.

**Comment by jerry2eden** [comment]
I reopened this request because @Justus-coded closed the request without actually merging the pull request. I will merge it after we have at least 5 reviews from team members

**Comment by bamid3l3** [comment]
Okay, that's fine..we can work with that

**Comment by zubbix** [comment]
It's okay. Thanks

**Comment by waleblaq** [comment]
good we could move ahead

**Pull request merged**
